### ISSUE TITLE
For "this site only" why would the preferences and the identifiers be needed?

### ISSUE THREAD

**Issue by jwrosewell** [prebid/paf-mvp-implementation#115]
https://github.com/prebid/paf-mvp-implementation/blob/9d197fc39a81d192f4a981b96e61611f772b5fd1/paf-mvp-frontend/src/lib/paf-lib.ts#L460

This requirement to need identifiers when "this site only" is set doesn't appear to align with my understanding.

We could create a bogus non PAF identifier for use when "this site only" is set to true to work around the requirement. However it will never pass validation as it won't be signed by a PAF Operator.

The alternative would be to change the relationship between preferences and identifiers so that they operate independently of one another.

**Comment by OlivierChirouze** [comment]
Can you elaborate what you mean by "this site only"?

**Comment by broggeri** [comment]
> This requirement to need identifiers when "this site only" is set doesn't appear to align with my understanding.
Hi James,
It sounds like you expect paf-lib to help handling site specific preferences, is that indeed your expectation ?

**Comment by jwrosewell** [comment]
@OlivierChirouze Publishers will not want to implement two different User Interfaces (aka CMPs) depending on whether the users wishes to participate in PAF, or not. If the user doesn't wish to participate then the UI needs to adapt to record the preferences only for the publisher web site in question. In that instance the data needs to be stored in 1P domain only cookies.

@broggeri There is an elegance in using the same data model for locally and globally scoped data. If that is not possible then we'll need separate data models for what is almost identical data.

**Comment by OlivierChirouze** [comment]
Also, preferences are designed to be signed with an id.

**Comment by jwrosewell** [comment]
This has been resolved by using a different model for "this site only" on/off. When off PAF is used. When on the TCF Core string is used. The publisher can specify the cookie in the configuration attribute "data-site-only-cookie-tcf-core". See the updated [developer documentation ](https://github.com/51Degrees/paf-mvp-implementation/blob/feature/pub-ad-dev-doc/paf-mvp-cmp/README.md)for more details.
