### ISSUE TITLE
Add a CONTRIBUTORS.md to list contributors and how to contact them

### ISSUE THREAD

**Issue by jwrosewell** [prebid/paf-mvp-implementation#186]
Will help users of the project know who to contact if they want assistance which might not be available from the core Prebid team. 

Relates to [this PR comment](https://github.com/prebid/paf-mvp-implementation/pull/180#discussion_r895458718).

**Comment by OlivierChirouze** [comment]
Good idea!
Feel free to introduce it in the mentioned PR ;-)

**Comment by jwrosewell** [comment]
Done in both repos.
